name: linuxscreentime
description: "A native glassmorphic Screen Time application for Linux environments."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Core background and tracking packages
  sqflite_common_ffi: ^2.3.4+1
  path: ^1.9.0
  fl_chart: ^0.66.0
  window_manager: ^0.3.8
  intl: ^0.20.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Explicitly declare the assets folder to bundle our tray icon assets
  assets:
    - assets/app_icon.png